<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aggregator\Authentication.Aggregator.csproj" />
    <ProjectReference Include="..\DTO\Authentication.DTO.csproj" />
    <ProjectReference Include="..\Handler\Authentication.Handler.csproj" />
    <ProjectReference Include="..\Repository\Authentication.Repository.csproj" />
    <ProjectReference Include="..\..\ServiceBus.Handlers\ServiceBus.Handlers.csproj" />
  </ItemGroup>

</Project>
