<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SharedSubsystem\SharedSubsystem.csproj" />
    <ProjectReference Include="..\..\ServiceBus.Handlers\ServiceBus.Handlers.csproj" />
    <ProjectReference Include="..\Aggregator\OrderManagement.Aggregator.csproj" />
    <ProjectReference Include="..\DTO\OrderManagement.DTO.csproj" />
    <ProjectReference Include="..\Repository\OrderManagement.Repository.csproj" />
  </ItemGroup>

</Project>
